name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Docker Tag override: [leave empty if not needed]'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - name: Get current version
      id: version
      run: echo "REPO_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    - name: Docker image tag override
      if: ${{ github.event.inputs.tags && github.event.inputs.tags != '' }}
      run: echo "REPO_VERSION=${{github.event.inputs.tags}}" >> $GITHUB_ENV
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_ORGANIZATION}}/${{secrets.DOCKER_REPO_NAME}}:$REPO_VERSION
    - name: Push Docker image
      run: docker push ${{secrets.DOCKER_ORGANIZATION}}/${{secrets.DOCKER_REPO_NAME}}:$REPO_VERSION
